# Generated by Django 2.2.7 on 2019-11-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('type', models.CharField(default='1', max_length=5)),
                ('state', models.CharField(default='ON', max_length=5)),
                ('user_id', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.Choice')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.Selection'),
        ),
    ]
